import sys
import random
import pyperclip

lorem = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet facilisis magna etiam tempor. Elementum pulvinar etiam non quam lacus suspendisse. Pellentesque dignissim enim sit amet venenatis urna. Elit sed vulputate mi sit amet mauris commodo quis. Commodo viverra maecenas accumsan lacus vel facilisis. Feugiat pretium nibh ipsum consequat nisl vel pretium. Magna fermentum iaculis eu non diam phasellus. Id semper risus in hendrerit gravida rutrum. In nisl nisi scelerisque eu ultrices vitae auctor eu augue. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Dui ut ornare lectus sit amet est placerat. Consequat mauris nunc congue nisi vitae suscipit tellus. Diam maecenas sed enim ut sem viverra aliquet eget sit. Lorem donec massa sapien faucibus et molestie ac feugiat. Viverra vitae congue eu consequat ac felis donec et. Nibh venenatis cras sed felis eget velit aliquet sagittis. Non diam phasellus vestibulum lorem sed risus ultricies tristique.",
    "Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Scelerisque eu ultrices vitae auctor eu. Eget arcu dictum varius duis at consectetur. Posuere sollicitudin aliquam ultrices sagittis. At erat pellentesque adipiscing commodo elit at imperdiet dui. Aliquet porttitor lacus luctus accumsan tortor posuere. At lectus urna duis convallis convallis tellus. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Non blandit massa enim nec dui nunc mattis enim. Ac odio tempor orci dapibus ultrices in.",
    "Mauris vitae ultricies leo integer malesuada. Vulputate eu scelerisque felis imperdiet proin. Lobortis scelerisque fermentum dui faucibus in. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Placerat vestibulum lectus mauris ultrices eros. Eget mauris pharetra et ultrices. Diam vel quam elementum pulvinar etiam. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Etiam tempor orci eu lobortis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Mattis nunc sed blandit libero volutpat sed cras. Turpis egestas sed tempus urna et pharetra pharetra. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Eleifend quam adipiscing vitae proin sagittis. Erat velit scelerisque in dictum non consectetur a. Vulputate dignissim suspendisse in est ante in nibh. Elementum integer enim neque volutpat ac tincidunt vitae semper. Quis vel eros donec ac odio tempor orci. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet.",
    "Velit egestas dui id ornare arcu odio ut sem. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Nisl nunc mi ipsum faucibus. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Sed ullamcorper morbi tincidunt ornare massa eget. Tristique nulla aliquet enim tortor at auctor. Adipiscing elit pellentesque habitant morbi. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Congue eu consequat ac felis donec. In hac habitasse platea dictumst. Facilisi etiam dignissim diam quis. Enim praesent elementum facilisis leo vel fringilla. Nulla facilisi etiam dignissim diam. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Id consectetur purus ut faucibus pulvinar elementum integer enim. Nibh ipsum consequat nisl vel pretium. Orci ac auctor augue mauris augue neque. Sit amet commodo nulla facilisi nullam vehicula ipsum.",
    "Malesuada bibendum arcu vitae elementum. Imperdiet massa tincidunt nunc pulvinar sapien. Orci eu lobortis elementum nibh tellus molestie. Vivamus at augue eget arcu dictum. Lorem dolor sed viverra ipsum nunc aliquet. Lorem donec massa sapien faucibus et molestie ac. At urna condimentum mattis pellentesque. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Tellus pellentesque eu tincidunt tortor. Nec tincidunt praesent semper feugiat. Pellentesque dignissim enim sit amet venenatis urna cursus. Scelerisque viverra mauris in aliquam. Sed enim ut sem viverra aliquet eget. Maecenas ultricies mi eget mauris.",
    "Tincidunt id aliquet risus feugiat in. Penatibus et magnis dis parturient montes nascetur. Quis lectus nulla at volutpat diam ut venenatis. Semper auctor neque vitae tempus quam. Amet luctus venenatis lectus magna fringilla urna porttitor. Tristique risus nec feugiat in. At consectetur lorem donec massa sapien faucibus et. At auctor urna nunc id cursus metus. Vitae ultricies leo integer malesuada nunc vel risus commodo. Est ullamcorper eget nulla facilisi etiam. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Ultrices tincidunt arcu non sodales neque sodales ut. Feugiat in fermentum posuere urna nec.",
    "Suspendisse interdum consectetur libero id faucibus nisl. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. In nisl nisi scelerisque eu ultrices vitae auctor eu. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Eget dolor morbi non arcu risus quis. Elit at imperdiet dui accumsan. Libero id faucibus nisl tincidunt eget nullam non nisi est. Suspendisse faucibus interdum posuere lorem ipsum dolor. Convallis a cras semper auctor. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Metus dictum at tempor commodo ullamcorper. Eu augue ut lectus arcu bibendum at varius. Massa eget egestas purus viverra accumsan. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Sollicitudin tempor id eu nisl. Lacus laoreet non curabitur gravida arcu.",
    "Aliquam malesuada bibendum arcu vitae elementum curabitur. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Diam volutpat commodo sed egestas egestas fringilla. Et netus et malesuada fames ac. Cursus sit amet dictum sit amet justo donec enim. Aliquam malesuada bibendum arcu vitae. Leo vel orci porta non pulvinar neque laoreet. Orci nulla pellentesque dignissim enim sit amet. Est velit egestas dui id ornare arcu odio. Bibendum arcu vitae elementum curabitur vitae. Quis imperdiet massa tincidunt nunc. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Vehicula ipsum a arcu cursus vitae. Amet mattis vulputate enim nulla aliquet porttitor lacus.",
    "Neque egestas congue quisque egestas diam in arcu. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Nec feugiat nisl pretium fusce id velit ut tortor. Dignissim diam quis enim lobortis scelerisque. Condimentum mattis pellentesque id nibh tortor. Risus quis varius quam quisque id diam vel quam elementum. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Diam quis enim lobortis scelerisque. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Lacus viverra vitae congue eu. Turpis egestas integer eget aliquet nibh praesent tristique. Feugiat in fermentum posuere urna nec.",
    "At in tellus integer feugiat scelerisque varius morbi enim nunc. Vestibulum morbi blandit cursus risus at ultrices. Condimentum lacinia quis vel eros donec. Neque ornare aenean euismod elementum nisi quis eleifend quam. Et sollicitudin ac orci phasellus. Laoreet non curabitur gravida arcu ac tortor dignissim. Pellentesque adipiscing commodo elit at imperdiet. Tellus in hac habitasse platea dictumst. Quisque sagittis purus sit amet volutpat consequat. At augue eget arcu dictum varius duis at. Mauris rhoncus aenean vel elit scelerisque mauris."
]
span = 100
start = 0


#for i in range(len(sys.argv)):
#    if (i != 0):
#        span = int(sys.argv[1])
        
            
chosen = random.choice(lorem)
words = chosen.split(" ")
sentence = ""
for i in range(span):
    sentence += words[i] + " "

pyperclip.copy(sentence)
